name: 'MA3 Plugin Release'
description: 'Auto generates the necessary XML files for grandMA3 plugins'
author: 'bootsie123'
branding:
  icon: 'package'
  color: 'red'
inputs:
  plugins:
    description:
      'An object defining the necessary data for each MA3 plugin being packaged'
    required: true
  outputFile:
    description: 'The name of the XML file to save to'
    required: true
  generateArtifact:
    description: 'True if an artifact should be generated, false if otherwise'
    required: false
runs:
  using: node20
  main: dist/index.js
